### ISSUE TITLE
Please show the counts in the confusion matrix by default

### ISSUE THREAD

**Issue by rhiever** [edublancas/sklearn-evaluation#20]
In your current example of the confusion matrix:

![image](https://cloud.githubusercontent.com/assets/1719223/15652280/23a168c6-2653-11e6-8034-0b2dc6902347.png)

it would be valuable to show the counts by default as well, as color does not effectively communicate exact values. The color is still useful for viewing general trends, however, so I think a combination of color + actual value would work best.

**Comment by edublancas** [comment]
Yes, definitely. I'll add that for the next release.

**Comment by edublancas** [comment]
Version 0.2.2 has a new colormap for confusion matrix and also shows numbers on the cells. https://raw.githubusercontent.com/edublancas/sklearn-evaluation/master/examples/cm.png
