### ISSUE TITLE
Visualize results of grid search?

### ISSUE THREAD

**Issue by rhiever** [edublancas/sklearn-evaluation#21]
Do you plan to add support for visualizing the results of a sklearn GridSearch, or is that out of the scope of this project? You could use line charts to visualize one parameter at a time, and heatmaps to visualize two parameters at a time.

**Comment by edublancas** [comment]
Yeah, I've been thinking about it and will add that in the near future.

**Comment by edublancas** [comment]
Added in 0.3 8dddda093555ec01547b0e305119f434ed315ac0
