### ISSUE TITLE
move to scikit-learn contrib?

### ISSUE THREAD

**Issue by amueller** [edublancas/sklearn-evaluation#25]
We have a scikit-learn-contrib organization now that could open this to a wider audience:
https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/README.md

**Comment by edublancas** [comment]
Thanks for the suggestion, I think it's a good idea. I'm still experimenting a bit with the API and there's some cleanup I need to do (remove legacy code mostly), after that I think the project will be in a better position for the migration.

**Comment by amueller** [comment]
Cool. I haven't had time to check out all your code in depth but it looks interesting. Going to scikit-learn-contrib will probably get you a lot of feedback.

**Comment by edublancas** [comment]
Hi, I left this for a while but I'm ready to work on it again. What's the workflow for moving this to sklearn-contrib?

I guess I first need to comply with specs in the template (https://github.com/scikit-learn-contrib/project-template), right?

**Comment by amueller** [comment]
check out the instructions here: https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/workflow.md
