### ISSUE TITLE
plot did not work 

### ISSUE THREAD

**Issue by albertyou2** [edublancas/sklearn-evaluation#27]
hi @edublancasx 
This repo is very useful for me ! Great work !
But I meet a very strange problem when I getting start to use sklearn-evaluation.

I run the code as below  to show the confusion matrix:
#code 
...
from sklearn_evaluation import plot
...
plot.confusion_matrix(y_true, y_pred, target_names=target_names)
...

But the plot window was not created .And there was not any error log .I'm sure the 'y_true' and 'y_pred' are both correct.

am I missing something?（sth like calling 'show()' etc?）
Thank you very much!

**Comment by edublancas** [comment]
Yes, If you are running this on the Python interpreter you need to use `plt.show()`, here's a working example:

```python
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split

from sklearn_evaluation import plot

data = datasets.make_classification(200, 10, 5, class_sep=0.65)
X = data[0]
y = data[1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

est = RandomForestClassifier()
est.fit(X_train, y_train)

y_pred = est.predict(X_test)
y_score = est.predict_proba(X_test)
y_true = y_test

plot.confusion_matrix(y_true, y_pred)
plt.show()
```

**Comment by albertyou2** [comment]
Thank you very much! It works!
