### ISSUE TITLE
Incompatibility with sklearn 0.20.0

### ISSUE THREAD

**Issue by mfaggin** [edublancas/sklearn-evaluation#30]
Hi.
I was trying to use this package with the up-to-dated version of scikit (0.20.0) but I did not understand how to do it. In particular, I was trying to use 

`from sklearn_evaluation import plot`
`plot.grid_search(gridCV.grid_scores_, change=change,kind='bar')`

but the member `grid_scores_` does not exist any more (present till scikit 0.17) and has been substituted by  `cv_results_`, which returns an object of different data type with respect to the former member.
Is there an easy way to go on using this function by using the new `cv_results_` in place of `grid_scores_`?
Thank you.

**Comment by edublancas** [comment]
Thanks for reporting this issue, I'll try to find some time to work on this. PRs are welcome!

**Comment by mfaggin** [comment]
That would be great!
If you agree, we should leave this issue open until you reply and I test your new solution.
Thnks a lot for your help.

**Comment by mfaggin** [comment]
Hi!
Do you have any news?
Just to know wheter you have some suggestions.
Thanks for your help.

**Comment by edublancas** [comment]
Hi, I haven't looked at this. I will have time to work on this two weeks from now.

**Comment by edublancas** [comment]
fixed on the master branch
