### ISSUE TITLE
Installing sklearn_evaluation

### ISSUE THREAD

**Issue by AminShah69** [edublancas/sklearn-evaluation#38]
I used "pip install sklearn-evaluation" to install this library in anaconda. All requirements exit but it does not install. When I want to import it, there is no library. 
When I run pip command to install it, it does not access to install, nor install anything.

**Comment by edublancas** [comment]
Hi,

Can you try this? If it doesn't work, please share the full output.

```sh
conda create --name skeval python=3.8 --yes
conda activate skeval
pip install git+https://github.com/edublancas/sklearn-evaluation
python -c "import sklearn_evaluation"
```

**Comment by AminShah69** [comment]
When I run `pip install git+https://github.com/edublancas/sklearn-evaluation`, I face the following error:
`
WARNING: Discarding pip install git+https://github.com/edublancas/sklearn-evaluation. Command errored out with exit status 1536: git clone -q pip install git+https://github.com/edublancas/sklearn-evaluation 'C:\User\Public\Documents\Wondershare\CreatorTemp\pip-req-build-bgq99jc' Check the logs for full command output
`

**Comment by edublancas** [comment]
Ok, that looks like an error on your end (it's not sklearn-evaluation).

Can you share the output of this?

```
conda create --name skeval python=3.8 --yes
conda activate skeval
# install from pypi instead of git
pip install sklearn-evaluation
python -c "import sklearn_evaluation"
```

**Comment by AminShah69** [comment]
Thank you so much. 
That works

**Comment by edublancas** [comment]
Sure!
