### ISSUE TITLE
GridSearch heatmap for 'None' parameter

### ISSUE THREAD

**Issue by shrsulav** [edublancas/sklearn-evaluation#39]
When I try to generate a heatmap for GridSearchCV results, if the parameter has 'None' type, it gives error:
`TypeError: '<' not supported between instances of 'NoneType' and 'int'`

The parameter can be, for e.g.
max_depth_for_decision_trees = [3, 5, 10, None].

Is there any workaround for this?

**Comment by abcnishant007** [comment]
I managed to get this working by adding a snippet to handle the `None` case. :) 
See this [answer](https://stackoverflow.com/a/68139645/3896008) on stackoverflow. Please let me know if it works for you. Then I will try to start a pull request here as well

**Comment by shrsulav** [comment]
@abcnishant007  Thanks for the solution.

**Comment by edublancas** [comment]
Thank you both! I'll make a release today with the fix.

**Comment by edublancas** [comment]
0.5.6 is out! :)
